# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb12c13d72350a23f670bc657b40d5c8ecc1599f9b9dc1e25b42560ddda33ffa53cb87b9869b1bc70bbf44f4955664462628dbfd4a0e612cc298d53766cbf7cc

test:
  secret_key_base: 361444b52d2775c0b1b50598fc2e5335f9588e812a545be676b3b74837b008b432cc8a9d828fe7f594ddf19861883efcdbd978cdf43d311c7a6f55a13e374d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
